### ISSUE TITLE
Error Missing dictionary English / Czech

### ISSUE THREAD

**Issue by elman22** [sc0ty/subsync#1]
Hi. Your idea with sub synchronization is brilliant. I immediately wanted to try it, but I quickly finished with error "Missing dictionary English / Czech". I could not find any documentation on how to fix it. Could you update read me or perhaps add FAQ about what to do in this case and what languages are supported?
Thanks, Elman

**Comment by sc0ty** [comment]
Thanks for your feedback.
Documentation is already being prepared.

You got this error because currently there is no translation for Czech language. All assets available to download are hosted [here](https://github.com/sc0ty/subsync/releases/tag/assets).
I thing I will change this message to be more verbose, explaining whats going on.
Currently all dictionaries are taken from http://kaiko.getalp.org/about-dbnary/download/ and as you can see, there is no Czech translations there.

I will try to find some dict database with compatible license. If you know any, please let me know (preferably not only Czech/English but also other Czech translations).

**Comment by sc0ty** [comment]
Added Czech/English dictionary from https://www.svobodneslovniky.cz/
Still looking for other dictionaries.

**Comment by elman22** [comment]
Perfect. Thank you very much. I was actually looking at dbnary and how to add another language to the parser, but I was unable to compile the project. Also when I looked over the code, it seemed quite complicated. So I'm grateful, that you were able to find that free dictionary. Again, thanks a lot.

**Comment by sc0ty** [comment]
You don't need dbnary, any dictionary would do, see https://github.com/sc0ty/subsync/blob/master/doc/assets.md

I'm still looking for dictionaries easy to convert. Found https://iate.europa.eu but it is oriented mainly for technical (and other) phrases, which poorly fits my use case.
