### ISSUE TITLE
All msi installers are prevented from running by Windows Defender SmartScreen

### ISSUE THREAD

**Issue by mertzi** [sc0ty/subsync#15]
I suspect they are false positives, but I do not dare to install subsync as it is now. Can you fix this?

**Comment by sc0ty** [comment]
Do you mean this complains about unrecognized app?
![Screenshot_2019-07-29_09-35-19](https://user-images.githubusercontent.com/1812478/62030069-81cf0a00-b1e4-11e9-9cc5-0b9fb131d4d4.png)

That's because SubSync is not signed with certificate required by Microsoft. I didn't signed it because certification is not free (its payed yearly) and this is non-commercial project, I don't want to invest my own money in it.

No antivirus (that I know of) is recognizing SubSync as a threat https://www.virustotal.com/gui/url/2fe4d7cf2738ea016145502efc8d136fe04cffafb6060e78f2db6ddf2d21f60c/detection but you still have to trust me to run my code on your machine.
