### ISSUE TITLE
Some feature requests/suggestions

### ISSUE THREAD

**Issue by bunchaiok** [sc0ty/subsync#17]
Thank you for this great program @sc0ty. Works nice and very user friendly too. I've been using it frequently and have some suggestions which I think can improve the program

- Please increase Max adjustment time there are a lot of movies that are longer than 3 hours
- When syncing SSA/ASS subtitles source their styles are lost in output. Can the program keep the source subtitles styles? 
- Can there be a Windows x64 portable version? So it can be self-contained in one folder and to move program and settings around computers easily
- How can I add or create my own dictionaries/speech related files for missing languages/assets?
- Sometimes subtitles will have synchronization points but program will say it failed to sync because there are not enough. Could there be a way to save the output regardless?

Batch processing related:
- Select All right-click option/Ctrl+A way to select all of same kind file. Like if I click subtitle and CTRL+A it will select all load subtitles. Currently it is not possible to do this after initial load
- Batch synchronization window only shows subtitle input name. Can it show reference also? Like subtitle.srt - reference.mkv. It makes it much easier to double check than batch processing window to see that subtitle is syncing to correct reference file.
- Effort setting is available in batch but not in single processing. Any reason for this?

Thank you again!

**Comment by sc0ty** [comment]
Thanks for your input.
* Maybe max adjustment slider should be exponential? Do you have any real use case when subtitles must be shift more than three hours? Usually I have 3-5 minutes mismatch max, and increasing this value would have significant impact on synchronization speed.
* I am using external libraries to handle subtitle files (ffmpeg for read and pysubs2 for write). Lacking style support is probably due to their limitations.
* I'd like to have portable version, some building scripts will have to be improved. Probably it will be done, eventually.
* Assets formats are described in [wiki](https://github.com/sc0ty/subsync/wiki/Assets)
* Save button is enabled based on some heuristics. You could use debug options to override this. In settings, debug tab select "enable advanced debug options" and you will see debug menu in synchronization window with option "enable save button". Don't expect miracles tho.

About batch processing: it is first release with this functionality and it still need some work.
* CTRL+A and some other shortcuts are on my todo list.
* Eventually I'd like to have single window for files selection an synchronization. Batch synchronization window is here only temporary. Ultimately synchronization status will be shown in the same three-column view.
* Effort in batch processing determines how fast synchronization should be terminated. In single shot mode you control it by stopping synchronization manually. Effort=0 is equivalent to stopping synchronization as soon as you got initial sync and save button enabled, effort=1 is when you wait till the end. You could check your subtitles first and decide to stop synchronization, or wait longer.

**Comment by bunchaiok** [comment]
Thanks for your reply and answers @sc0ty. 

About adjustment time - Sorry, I totally misunderstood/misread this function. I thought it meant runtime of the reference file not mismatch time difference. In that case it does seem that only few videos will need more time (maybe for long livestreams/videos). It might be a good idea to increase it anyhow if the current limit is arbitrary but it's your choice.
About styles - That's too bad, hopefully in the future the libraries will have some way to retain the styles.
About assets - I was actually meaning about assets/dictionaries of languages missing from the currently available assets. Are those missing languages assets able to be the created by users somehow?
About single window for synchronization - I see. It will be interesting to see how this will look.

I also want to ask what you think about a feature to automatically mux the synchronized subtitles with the reference file to create an output file with reference file + synchronized subtitles?

**Comment by sc0ty** [comment]
About assets: I am using dictionaries mainly from Wiktionary and IATE. Currently I'm rewriting converting scripts to automate this process. It will be commited to repo if you are interested.
About speech recognition languages, I am using most of the models available on the internet for CMUSphinx. I've never created such model myself.
I've designed dictionary format myself so you won't find any files except for these used by subsync. Speech recognition models have additional yaml file with configuration specific for subsync.

About styles: I can see that FFMPEG returns style names so probably there is also API for retrieving styles description. I will look into this, but currently there are other things on my priority list.

I won't do any muxing functionality. It would take lots of time and complicate application design. Use some external tool to do that.

**Comment by sc0ty** [comment]
I've made styles working. It turns out that I just need to pass them from ffmpeg to pysubs2.
I am experimenting mainly with SubRip format which doesn't support styling, that's why I haven't notice this problem before.

**Comment by bunchaiok** [comment]
>About assets: I am using dictionaries mainly from Wiktionary and IATE. Currently I'm rewriting converting scripts to automate this process. It will be commited to repo if you are interested.

That would be very helpful, thanks.

>I won't do any muxing functionality. It would take lots of time and complicate application design. Use some external tool to do that.

I see. It would be a nice to have feature but I understand your concern. 

>I've made styles working. It turns out that I just need to pass them from ffmpeg to pysubs2.

That is great @sc0ty, can't wait to try it.

**Comment by sc0ty** [comment]
I've just released version 0.11 which should have working SSA/ASS styles

**Comment by bunchaiok** [comment]
Thanks @sc0ty. I tested with some SSA/ASS files and styles works mostly. I did notice some things that differed in output subtitle file compared with input
- Some types of lines under [Events] such as `Comment:...` if it is in the original ASS file is not there at all in the output file.
- There is no new line between [Events] last line and Dialogue
- In output file some numbers append `.0` to end of the number while in other places of same file the same number doesn't have anything appended (which is how it is in the input ASS file). 

I don't know if the last two matter (maybe some players are strict about these for correctly playing the subtitles) but just letting you know

Also one thing unrelated, in batch processing is it possible to make dragging subtitle/reference files up or down fully? Currently you can only drag to end of visible window, use scrollbar to scroll down, drag to end of visible window and repeat.

**Comment by sc0ty** [comment]
I am parsing subtitles and then constructing new ones, so some differences are to be expected (as long as its still valid ASS file).
Comments are stripped by ffmpeg since they are comments. I can't do anything about it.

Dragging with scrolling file list is also on my todo list.

**Comment by sc0ty** [comment]
There is now portable version.
Batch select and sync windows are now merged to single window, with working keyboard shortcuts.
Auto scrolling is not yet implemented, but we will get there eventually.

I am closing this now since it is not single issue/feature request.
