### ISSUE TITLE
Command line option / mode? 

### ISSUE THREAD

**Issue by Alekzanther** [sc0ty/subsync#3]
A command line only option/mode would be awesome. Was looking through the source code and there's some stuff happening with args, but I can't get it to run on my server (seems like it tries to throw up some GUI for it anyways.)  

It would be really handy if one could just:
`subsync video-file subtitle-file synced-subtitle-file`

Would make it easy to integrate this in some script and automate things.

**Comment by sc0ty** [comment]
There are command line arguments implemented, but are still running with GUI. I made this mostly for debugging and testing than anything else (faster re-running app with the same files and config). Since GUI is firmly rooted in subsync, I was thinking maybe I will someday make another version with command line interface. But it is not my priority right now.

Anyway you could use it with GUI, e.g.
`subsync.py --sub="subs.srt" --sub-stream=1 --sub-lang=pol --ref="movie.avi" --ref-stream=2 --ref-lang=eng --out="out.srt" --auto=done`

--auto=done means it will terminate when done

It lacks documentation, but you could try `subsync --help`.
Also you could enable logs and, look for RUNCMD entry (at synchronization start) - it is command to re-run current synchronization.

**Comment by Alekzanther** [comment]
Alright! I'll check those args out.
