### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by HeresJonny** [sc0ty/subsync#6]
Not an issue but a support request. I've installed the latest .msi and downloaded some speech models. Upon trying to sync, the program tells me that it can't find the english speed model. I've tried copying a speech folder in various places but no joy. Where do the assets go? Thanks in advance!

**Comment by HeresJonny** [comment]
Oops, sorry... must have been a firewall issue - it now autodownloads.

**Comment by sc0ty** [comment]
I will add different error message for situation like this since it could be confusing.

For people who came here from Google, assets are:
- on Windows in `C:\ProgramData\subsync\assets`,
- on Snap installation in `~/snap/subsync/current/.config/subsync/assets` (or whenever snap settings are in your system,
- on other Linux installation in `~/.config/subsync/assets`
