### ISSUE TITLE
bazarr feature 

### ISSUE THREAD

**Issue by rigas40** [sc0ty/subsync#63]
Is possible add feature for detect new subtitles from bazarr and check if is ok or not ok

if is ok leave
if not sync sub

**Comment by sc0ty** [comment]
I've never used bazarr, but see [here](https://github.com/sc0ty/subsync/issues/44#issuecomment-571707924). He is using subsync under docker in [command line mode](https://github.com/sc0ty/subsync/wiki/Command-line-options).

**Comment by rigas40** [comment]
thank you sir
And if you add monitor folder function with Scan Recursively ?

**Comment by sc0ty** [comment]
What do you mean by monitor folder function?
I'm not planning to add any background running service functionality for subsync.
And I think it would be better to use some shell scripting for recursive scanning folder, since you could have different requirement of how to pair subtitles with references, not to mention other properties like streams and languages.
