### ISSUE TITLE
Batch processing by parent folder, recursive

### ISSUE THREAD

**Issue by jobrien2001** [sc0ty/subsync#71]
Hello,

The current batch processing by command line is too complicated, it should be easier for the user.  Having to populate a list of movies in a yaml file can be too much work depending on the work load.

It would be nice to specify a parent folder where the video folders reside and the subsync to recursive search for subtitles, match them to the video, an option to use first audio track set language or autodetect audio language, and then process the subtitles files.

I thought about writing a script that would do this, looping through folders with ffprobe to extract track information and execute 1 subsync instance for every subtitle found.  However this could be native in subsync and not through some external solution.

Any feedback would be great

**Comment by sc0ty** [comment]
You could add folder from GUI (recursively) and then match subtitles with video, select tracks and languages etc.
I don't wan't to add anything similar in headless mode since it would be hard to cover everyone's use cases, and would probably result in multitude poorly tested switches.

And you don't need ffprobe, you could left tracks unspecified, subsync will select them automatically. Since last version you could also select track by type or language, see https://github.com/sc0ty/subsync/wiki/Command-line-options.

**Comment by jobrien2001** [comment]
Thank you for your response.

It is not clear for me when you say select track by type.  I would imagine sub or audio?  The wiki mentions language

> --ref-stream-by-type TYPE - select stream by language (optional);

**Comment by sc0ty** [comment]
It's a typo, should be `--ref-stream-by-type=sub/audio`, corrected.
